### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by freddy79hotmail** [iAlexeyProkhorov/qBoSlider#5]
An error occurred while starting the application.
FormatException: Input string was not in a correct format.

System.Text.StringBuilder.FormatError()

    FormatException: Input string was not in a correct format.
        System.Text.StringBuilder.FormatError()
        System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, string format, ParamsArray args)
        string.FormatHelper(IFormatProvider provider, string format, ParamsArray args)
        string.Format(string format, object arg0)
        Nop.Services.Plugins.PluginService.InstallPlugins() in PluginService.cs
        Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions.StartEngine(IApplicationBuilder application) in ApplicationBuilderExtensions.cs
        Nop.Web.Startup.Configure(IApplicationBuilder application) in Startup.cs
        System.RuntimeMethodHandle.InvokeMethod(object target, object[] arguments, Signature sig, bool constructor, bool wrapExceptions)
        System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
        Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(object instance, IApplicationBuilder builder)
        Microsoft.AspNetCore.Hosting.ConfigureBuilder+<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
        Microsoft.AspNetCore.Hosting.GenericWebHostBuilder+<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
        Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter+<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
        Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter+<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
        Microsoft.AspNetCore.HostFilteringStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
        Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
        Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
        Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
        Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
        Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
        Nop.Web.Program.Main(string[] args) in Program.cs

Show raw exception

System.FormatException: Input string was not in a correct format.

   at System.Text.StringBuilder.FormatError()

   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)

   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)

   at System.String.Format(String format, Object arg0)

   at Nop.Services.Plugins.PluginService.InstallPlugins() in C:\andrei\nop_sources\src\Libraries\Nop.Services\Plugins\PluginService.cs:line 489

   at Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions.StartEngine(IApplicationBuilder application) in C:\andrei\nop_sources\src\Presentation\Nop.Web.Framework\Infrastructure\Extensions\ApplicationBuilderExtensions.cs:line 67

   at Nop.Web.Startup.Configure(IApplicationBuilder application) in C:\andrei\nop_sources\src\Presentation\Nop.Web\Startup.cs:line 59

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)

   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)

   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)

   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)

   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)

   at Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)

   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)

   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)

   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)

   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)

   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)

   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)

   at Nop.Web.Program.Main(String[] args) in C:\andrei\nop_sources\src\Presentation\Nop.Web\Program.cs:line 12

**Comment by iAlexeyProkhorov** [comment]
Hi! Sorry, can't restore this exception. If you've some free time please describe me environment that you use(Windows/linux), may be some changes in plugin sources?

**Comment by freddy79hotmail** [comment]
hello, first of all I wanted to express my appreciation for your work.  i use iis 8 on win server 2016
-------- Messaggio originale --------Da: iAlexeyProkhorov ***@***.***> Data: 26/07/21  13:13  (GMT+01:00) A: iAlexeyProkhorov/qBoSlider ***@***.***> Cc: freddy79hotmail ***@***.***>, Author ***@***.***> Oggetto: Re: [iAlexeyProkhorov/qBoSlider] Problem with installation, 4.3 version (#5) 
Hi! Sorry, can't restore this exception. If you've some free time please describe me environment that you use(Windows/linux), may be some changes in plugin sources?

**Comment by iAlexeyProkhorov** [comment]
> hello, first of all I wanted to express my appreciation for your work.  i use iis 8 on win server 2016 -------- Messaggio originale --------Da: iAlexeyProkhorov ***@***.***> Data: 26/07/21 13:13 (GMT+01:00) A: iAlexeyProkhorov/qBoSlider ***@***.***> Cc: freddy79hotmail ***@***.***>, Author ***@***.***> Oggetto: Re: [iAlexeyProkhorov/qBoSlider] Problem with installation, 4.3 version (#5) Hi! Sorry, can't restore this exception. If you've some free time please describe me environment that you use(Windows/linux), may be some changes in plugin sources? —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you that use **qBoSlider**. Unfortunately I still can't restore this exception. May be some other third part plugin changes some nopCommerce logic.
What qBoSlider version did you use?
